export const cdfTemplate = {
  token: null,
  f: "json",
  service: {
    serviceName: null,
    type: "FeatureServer",
    description: "here is a sample description",
    capabilities: "Query",
    provider: "CUSTOMDATA",
    clusterName: "default",
    minInstancesPerNode: 0,
    maxInstancesPerNode: 0,
    instancesPerContainer: 1,
    maxWaitTime: 60,
    maxStartupTime: 300,
    maxIdleTime: 1800,
    maxUsageTime: 600,
    loadBalancing: "ROUND_ROBIN",
    isolationLevel: "HIGH",
    configuredState: "STARTED",
    recycleInterval: 24,
    recycleStartTime: "00:00",
    keepAliveInterval: 1800,
    private: false,
    isDefault: false,
    maxUploadFileSize: 0,
    allowedUploadFileTypes: "",
    properties: { disableCaching: "true" },
    jsonProperties: {
      customDataProviderInfo: {
        dataProviderName: "analytics",
        dataProviderHost: "",
        dataProviderId: "",
      },
    },
    extensions: [],
    frameworkProperties: {},
    datasets: [],
  },
};
